# fly.toml app configuration file generated for apijh on 2024-01-16T14:17:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apijh"
primary_region = "lhr"

[build]
  image = "platinumsoft/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51OXlUdCEVVNDFtH1DiqKINEkEpmyATOKaPegLZe2VEcfKx7FRRE1tAOwVbBEW848kjvMKEBfLhWk5rRUbwgEm0ub00UV2EWHoB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
